[Appearance]
color_scheme_path=/home/doodlebob/.config/qt6ct/colors/slicedlabs.conf
custom_palette=true
icon_theme=Tela-circle-purple-dark
standard_dialogs=default
style=Fusion

[Interface]
cursor_flash_time=1000
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=2
wheel_scroll_lines=3
