// GENERATED by render-keys from system/keys.toml — do not edit.
#set page(width: 420mm, height: 297mm, margin: 18mm, fill: rgb("#1E1E1E"))
#set text(font: "Geist Mono", fill: rgb("#F7F6F2"), size: 9pt)

#let cap(label, sub, fill, ink) = rect(
  width: 26mm, height: 16mm, inset: 2mm, radius: 3pt, fill: fill,
  stroke: 0.5pt + rgb("#ffffff22"))[
  #set text(fill: ink)
  #text(weight: 700, size: 11pt)[#label] \
  #text(size: 6.5pt, fill: ink)[#sub]
]
#let blank(label) = rect(width: 26mm, height: 16mm, inset: 2mm, radius: 3pt,
  fill: rgb("#2B2B2B"), stroke: 0.5pt + rgb("#ffffff11"))[
  #text(weight: 400, size: 11pt, fill: rgb("#B8A789"))[#label]]

#align(center)[#text(size: 22pt, weight: 800)[SlicedLabs OS — Keyboard Map]]
#v(4mm)

#text(size: 14pt, weight: 700)[Mod]
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("1", "coding", rgb("#378ADD"), rgb("#1E1E1E")), cap("2", "research", rgb("#7F77DD"), rgb("#1E1E1E")), cap("3", "engine", rgb("#D85A30"), rgb("#1E1E1E")), cap("4", "browser", rgb("#1D9E75"), rgb("#1E1E1E")), cap("5", "monitoring", rgb("#639922"), rgb("#1E1E1E")), cap("6", "streaming", rgb("#D4537E"), rgb("#1E1E1E")), cap("7", "gaming", rgb("#E24B4A"), rgb("#1E1E1E")), cap("8", "media", rgb("#BA7517"), rgb("#1E1E1E")), cap("9", "desk (blank ·", rgb("#C264B0"), rgb("#1E1E1E")), blank("0"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("Q", "Close focused", rgb("#2961B1"), rgb("#1E1E1E")), cap("W", "Toggle floating", rgb("#2961B1"), rgb("#1E1E1E")), cap("E", "engine", rgb("#D85A30"), rgb("#1E1E1E")), cap("R", "Cycle column", rgb("#2961B1"), rgb("#1E1E1E")), blank("T"), blank("Y"), blank("U"), blank("I"), blank("O"), blank("P"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("A"), blank("S"), cap("D", "coding /", rgb("#378ADD"), rgb("#1E1E1E")), cap("F", "Fullscreen", rgb("#2961B1"), rgb("#1E1E1E")), cap("G", "Gaming: focus", rgb("#E24B4A"), rgb("#1E1E1E")), cap("H", "Focus column", rgb("#2961B1"), rgb("#1E1E1E")), cap("J", "Focus window", rgb("#2961B1"), rgb("#1E1E1E")), cap("K", "Focus window up", rgb("#2961B1"), rgb("#1E1E1E")), cap("L", "Focus column", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("Z"), blank("X"), cap("C", "research", rgb("#7F77DD"), rgb("#1E1E1E")), cap("V", "media (mnemonic)", rgb("#BA7517"), rgb("#1E1E1E")), cap("B", "browser", rgb("#1D9E75"), rgb("#1E1E1E")), blank("N"), cap("M", "monitoring", rgb("#639922"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("↵", "Open a terminal", rgb("#2961B1"), rgb("#1E1E1E")), cap("␣", "App launcher", rgb("#2961B1"), rgb("#1E1E1E")), cap("⇥", "Cycle forward", rgb("#2961B1"), rgb("#1E1E1E")), cap("Esc", "Lock screen", rgb("#2961B1"), rgb("#1E1E1E")), cap("⌫", "Dismiss all", rgb("#2961B1"), rgb("#1E1E1E")), cap("/", "Cockpit ☰", rgb("#2961B1"), rgb("#1E1E1E")), cap(",", "Consume window", rgb("#2961B1"), rgb("#1E1E1E")), cap(".", "Expel window", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#v(8mm)

#text(size: 14pt, weight: 700)[Mod+Shift]
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("1", "Move column →", rgb("#378ADD"), rgb("#1E1E1E")), cap("2", "Move column →", rgb("#7F77DD"), rgb("#1E1E1E")), cap("3", "Move column →", rgb("#D85A30"), rgb("#1E1E1E")), cap("4", "Move column →", rgb("#1D9E75"), rgb("#1E1E1E")), cap("5", "Move column →", rgb("#639922"), rgb("#1E1E1E")), cap("6", "Move column →", rgb("#D4537E"), rgb("#1E1E1E")), cap("7", "Move column →", rgb("#E24B4A"), rgb("#1E1E1E")), cap("8", "Move column →", rgb("#BA7517"), rgb("#1E1E1E")), cap("9", "Move column →", rgb("#2961B1"), rgb("#1E1E1E")), blank("0"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("Q", "Quit niri (exit", rgb("#2961B1"), rgb("#1E1E1E")), cap("W", "Random wallpaper", rgb("#D85A30"), rgb("#1E1E1E")), cap("E", "Move column →", rgb("#D85A30"), rgb("#1E1E1E")), blank("R"), blank("T"), blank("Y"), blank("U"), blank("I"), blank("O"), blank("P"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("A"), cap("S", "Screenshot", rgb("#2961B1"), rgb("#1E1E1E")), cap("D", "Move column →", rgb("#378ADD"), rgb("#1E1E1E")), cap("F", "Maximize column", rgb("#2961B1"), rgb("#1E1E1E")), cap("G", "Gaming launcher", rgb("#E24B4A"), rgb("#1E1E1E")), cap("H", "Move column left", rgb("#2961B1"), rgb("#1E1E1E")), cap("J", "Move window down", rgb("#2961B1"), rgb("#1E1E1E")), cap("K", "Move window up", rgb("#2961B1"), rgb("#1E1E1E")), cap("L", "Move column", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("Z"), blank("X"), cap("C", "Move column →", rgb("#7F77DD"), rgb("#1E1E1E")), cap("V", "Move column →", rgb("#BA7517"), rgb("#1E1E1E")), cap("B", "Move column →", rgb("#1D9E75"), rgb("#1E1E1E")), blank("N"), cap("M", "Move column →", rgb("#639922"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("⇥", "Cycle backward", rgb("#2961B1"), rgb("#1E1E1E")), cap("Esc", "Power menu", rgb("#2961B1"), rgb("#1E1E1E")), cap("/", "niri's built-in", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#v(8mm)

#text(size: 14pt, weight: 700)[Mod+Ctrl]
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("1"), blank("2"), blank("3"), blank("4"), blank("5"), blank("6"), blank("7"), blank("8"), blank("9"), blank("0"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("Q"), blank("W"), cap("E", "Stage scene:", rgb("#D85A30"), rgb("#1E1E1E")), blank("R"), blank("T"), blank("Y"), blank("U"), blank("I"), blank("O"), blank("P"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("A"), cap("S", "Stage scene:", rgb("#D4537E"), rgb("#1E1E1E")), cap("D", "Stage scene:", rgb("#378ADD"), rgb("#1E1E1E")), blank("F"), cap("G", "Toggle GameMode", rgb("#E24B4A"), rgb("#1E1E1E")), blank("H"), blank("J"), blank("K"), blank("L"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("Z"), blank("X"), cap("C", "Stage scene:", rgb("#7F77DD"), rgb("#1E1E1E")), cap("V", "Stage scene:", rgb("#BA7517"), rgb("#1E1E1E")), cap("B", "Stage scene:", rgb("#1D9E75"), rgb("#1E1E1E")), blank("N"), cap("M", "Stage scene:", rgb("#639922"), rgb("#1E1E1E")))
#v(2mm)
#v(8mm)

#text(size: 14pt, weight: 700)[Mod+Alt]
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("1"), blank("2"), blank("3"), blank("4"), blank("5"), blank("6"), blank("7"), blank("8"), blank("9"), blank("0"))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("Q"), blank("W"), cap("E", "Open the", rgb("#D85A30"), rgb("#1E1E1E")), blank("R"), cap("T", "HUD inspector:", rgb("#D98AAE"), rgb("#1E1E1E")), cap("Y", "HUD inspector:", rgb("#B8A789"), rgb("#1E1E1E")), blank("U"), cap("I", "HUD inspector:", rgb("#2961B1"), rgb("#1E1E1E")), blank("O"), cap("P", "Music cockpit", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("A", "HUD inspector:", rgb("#C264B0"), rgb("#1E1E1E")), cap("S", "SlicedLabs", rgb("#2961B1"), rgb("#1E1E1E")), blank("D"), blank("F"), blank("G"), blank("H"), blank("J"), cap("K", "Keybindings", rgb("#2961B1"), rgb("#1E1E1E")), cap("L", "Toggle dark /", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, blank("Z"), blank("X"), cap("C", "Control Center", rgb("#BA7517"), rgb("#1E1E1E")), blank("V"), blank("B"), cap("N", "HUD inspector:", rgb("#2FA39A"), rgb("#1E1E1E")), cap("M", "HUD inspector:", rgb("#BA7517"), rgb("#1E1E1E")))
#v(2mm)
#stack(dir: ltr, spacing: 2mm, cap("␣", "Command palette", rgb("#2961B1"), rgb("#1E1E1E")))
#v(2mm)
#v(8mm)

#text(size: 14pt, weight: 700)[Function & media keys]
#v(2mm)
#text(size: 9pt)[`Print` — Screenshot (region picker)] \
#text(size: 9pt)[`Shift+Print` — Screenshot whole screen] \
#text(size: 9pt)[`XF86AudioRaiseVolume` — Volume up] \
#text(size: 9pt)[`XF86AudioLowerVolume` — Volume down] \
#text(size: 9pt)[`XF86AudioMute` — Mute output] \
#text(size: 9pt)[`XF86AudioMicMute` — Mute microphone] \
#text(size: 9pt)[`XF86AudioPlay` — Play / pause (MPRIS — whatever is playing)] \
#text(size: 9pt)[`XF86AudioNext` — Next track (MPRIS)] \
#text(size: 9pt)[`XF86AudioPrev` — Previous track (MPRIS)] \
#text(size: 9pt)[`Mod+F12` — Toggle MangoHud overlay (sends F12)] \
