#!/usr/bin/env bash
# SlicedLabs · body · © 2026 SlicedLabs
# glyphs.sh — GENERATED from system/tokens.toml [icon] via render-templates.
#
# Do NOT edit this file directly — edit tokens.toml [icon] then re-render.
# Source it in any module script to bind to the single icon vocabulary that
# also drives the CSS classes and Niri:
#
#   source "$HOME/.config/quickshell/cockpit/scripts/lib/glyphs.sh"
#
# Icons are then $G_OK, $G_ENGINE, $G_MIC, … and g_spin <tick> for the
# braille spinner frame.

# --- State vocabulary (mirrors .empty/.ok/.info/.alert/.critical) -----------
G_OK="✓"
G_FAIL="✗"
G_IDLE="·"
G_INFO="󰋽"
G_ALERT="󰀦"
G_CRIT="󰀪"
G_BUILD="󱥸"
G_SPINNER="⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

# --- Tab identities ---------------------------------------------------------
G_ENGINE="󰒋"
G_COMMS="󰭹"
G_STREAM="󰕧"
G_MONITORING="󰓅"
G_GAMING="󰊴"
G_CODING="󰨸"
G_BROWSER="󰈹"
G_MEDIA="󰎆"
G_NET="󰛳"
G_AI="󰚩"
G_AGENDA="󰃭"

# --- Shared metric glyphs ---------------------------------------------------
G_CLOCK="󰥔"
G_CPU="󰻠"
G_MEM="󰍛"
G_TEMP="󰔏"
G_DISK="󰋊"
G_NET_DOWN="󰇚"
G_NET_UP="󰕒"
G_MIC="󰍬"
G_MUTE="󰍭"
G_REC="⏺"
G_LIVE="󰐰"
G_GPU="󰢮"
G_BATTERY="󰁹"
G_BELL="󰂚"
G_MAIL="󰇮"
G_VPN="󰦝"
G_LOCK="󰌾"
G_GIT="󰊢"
G_POMO="󰔛"
G_SPEND="󰉁"
G_PLAY="󰐊"
G_PAUSE="󰏤"
G_SPEAKER="󰕾"
G_FIREWALL="󰞀"
G_ROUTE="󰑪"

# g_spin <tick> — emit one braille spinner frame for the given tick counter.
# Uses awk substr (UTF-8 aware under gawk) so multibyte braille is safe.
g_spin() {
    awk -v s="$G_SPINNER" -v i="${1:-0}" 'BEGIN { n = length(s); printf "%s", substr(s, (i % n) + 1, 1) }'
}
